[build]
  publish = "public"
  command = ""
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = ""

[context.branch-deploy]
  command = ""
