"""Demo script data: the flows the PDF requires (success, duplicate, failure, ambiguous/unsafe AI) and a few extra,
each pointing at golden scenarios and recorded model outputs, plus drills for 'we change one assumption'."""
from __future__ import annotations

DEMO_FLOWS = [
    {"id": "D1", "title": "Successful end-to-end flow with grounded personalization",
     "pdf_requirement": "at least one successful flow", "golden": ["G080"], "recordings": ["EV-G080:good"],
     "show": ["event arrives (list import) -> persisted", "state loaded: account + contacts + facts",
              "rules: ELIGIBLE, best contact = finance director", "AI drafts copy citing usable fact_ids only",
              "validator accepts -> approved template + grounded opening", "send inside the recipient's window",
              "audit row: event, state version, decision, reasons, model output, validation verdict, action"],
     "expected_audit": ["received", "decided:contact", "ai_draft:accept", "sent"]},
    {"id": "D2", "title": "Duplicate delivery",
     "pdf_requirement": "one duplicate event", "golden": ["G040", "G041", "G042"], "recordings": [],
     "show": ["same webhook delivered twice -> second is ignored", "same idempotency key with a new event_id -> ignored",
              "CRM mirror with another key -> deduped by content", "exactly one email, one audit trail"],
     "expected_audit": ["received", "decided:contact", "sent", "duplicate_ignored"]},
    {"id": "D3", "title": "Failure: transient error and uncertain outcome",
     "pdf_requirement": "one realistic failure scenario", "golden": ["G070", "G072", "G075"], "recordings": [],
     "show": ["send API 503 -> backoff, retry, ONE email (idempotency key reused)",
              "send API 200 + status=unknown -> reconcile by key before any retry, never blind re-send",
              "enrichment keeps failing -> retry budget spent -> dead-letter + alert + human"],
     "expected_audit": ["send_attempt_1:error", "send_attempt_2:ok", "sent"]},
    {"id": "D4", "title": "Ambiguous / unsafe AI output",
     "pdf_requirement": "one ambiguous or unsafe AI case",
     "golden": ["G064", "G065", "G067"],
     "recordings": ["EV-R-MIX-01:overconfident_wrong_label", "EV-R-INJ-01:obeys_injection",
                    "EV-R-AMB-03:good", "EV-R-AMB-03:wrong_but_valid_overconfident"],
     "show": ["'me interesa pero no me escriban' -> model says INTERESADO at 0.96; deterministic opt-out guard overrides -> suppress",
              "prompt injection in the reply -> model obeys -> validator rejects -> human",
              "ambiguous reply at low confidence -> human, never auto-acts",
              "HONEST LIMIT: a plausible but wrong, schema-valid answer passes; only labelled evals and human sampling catch it"],
     "expected_audit": ["ai_output:valid", "guard:G001", "decided:suppress"]},
    {"id": "D5", "title": "Malformed AI output",
     "pdf_requirement": "AI output may be incomplete, malformed or unsupported by the data",
     "golden": ["G063", "G066"],
     "recordings": ["EV-R-AHN-01:truncated_json", "EV-R-AHN-01:date_invented", "EV-R-PER-01:hallucinated_referral_email",
                    "EV-R-INT-13:qualification_hallucinated"],
     "show": ["truncated JSON -> retry once -> escalate", "invented date / referral / team size not in the text -> escalate, no retry"],
     "expected_audit": ["ai_output:invalid", "retry_1", "escalated"]},
    {"id": "D6", "title": "Out-of-order race (late unsubscribe)",
     "pdf_requirement": "events may arrive delayed or out of order", "golden": ["G047", "G048"], "recordings": [],
     "show": ["targeting processed first (state looked eligible)", "unsubscribe that happened BEFORE arrives 20h later",
              "apply it, suppress, cancel any pending send"],
     "expected_audit": ["decided:contact", "late_event", "suppressed", "pending_cancelled"]},
]

ASSUMPTION_DRILLS = [
    {"change": "Cool-down after outreach goes from 14 to 30 days", "where": "config.RECENT_OUTREACH_DAYS + policy caps",
     "proof": "boundary goldens G009/G010 flip; re-run oracle + tests"},
    {"change": "AI may no longer suppress on its own (or may, with 100% human review)", "where": "send_policy.ai_autonomy",
     "proof": "recordings D4: opt-out guard already deterministic"},
    {"change": "Volume grows 10x (500k accounts/month)", "where": "python -m generator build --n 500000",
     "proof": "burst of ~100k events/20 min per list drop; check queue depth, rate limits in send_policy.api_limits"},
    {"change": "Second channel (WhatsApp) added", "where": "send_policy.channel + templates + opt-out rules per channel",
     "proof": "templates.jsonl pattern; golden opt-out must apply across channels"},
    {"change": "Enrichment provider becomes unreliable", "where": "mock_behavior distribution in config.ENRICH_BEHAVIORS",
     "proof": "G074-G077; retry budget and dead-letter path"},
    {"change": "SDR capacity doubles", "where": "impact.ASSUMPTIONS.control.coverage_of_eligible",
     "proof": "impact_example.md: incremental pipeline shrinks, the measurement design is unchanged"},
]
