"""Everyday-language names for actions and reason codes, for the web page. One source; exported to public/data."""
ACTIONS = {
    "contact": ["Personal first email", "Passed every check and is worth a personal first email. It is prepared and recorded (simulated: nothing is ever sent)."],
    "nurture": ["Slow follow-up (nurture)", "Eligible, but a weak fit for now. No first email and no AI: it joins a slow automatic follow-up and is scored again at the next event."],
    "wait": ["On hold", "Not the right moment (recently contacted or recently lost). The system waits and checks again."],
    "suppress": ["Do not contact", "Should not receive outreach (opted out, customer, competitor, open deal or poor fit)."],
    "handoff_ae": ["Hand to a sales exec", "Already has an owner, so it goes to the right sales exec instead of an automatic email."],
    "enrich": ["Needs better data first", "Data is missing or outdated, so the system looks it up before doing anything else."],
    "escalate_human": ["A person decides", "Conflicting or unusual situation. The system does not guess."],
}
CODES = {
    "ELIGIBLE": "Passed every check",
    "UNSUBSCRIBED": "Asked to stop receiving emails",
    "HARD_BOUNCE": "Its email address does not exist",
    "SPAM_COMPLAINT": "Marked a previous email as spam",
    "DNC": "Asked not to be contacted",
    "LEGAL_HOLD": "Legal hold on the account",
    "COMPETITOR": "Competitor",
    "STATE_CONFLICT": "The CRM contradicts itself (customer without a won deal, or the reverse)",
    "CUSTOMER": "Already a customer",
    "CHURNED_CUSTOMER": "Former customer",
    "DUPLICATE_ACCOUNT": "Duplicate of an older account",
    "ACTIVE_OPPORTUNITY": "Has a deal in progress",
    "AE_ASSIGNED": "Already assigned to a sales exec",
    "NO_AE_AVAILABLE": "No sales exec available right now",
    "CLOSED_LOST_COOLDOWN": "Lost a deal recently",
    "NOT_ICP": "Too small or not a target industry",
    "RECENT_OUTREACH": "Contacted very recently",
    "SEQUENCE_EXHAUSTED": "Already received the full email sequence",
    "STALE_ENRICHMENT": "Company data is out of date",
    "MISSING_FIRMOGRAPHICS": "Company size or industry is missing",
    "NO_CONTACTS": "No contact person on file",
    "UNVERIFIED_EMAIL_ONLY": "Only unverified email addresses",
    "NO_VALID_EMAIL": "No valid email address",
    "ENRICHMENT_EXHAUSTED": "Data lookups did not fix it",
    "LOW_PRIORITY": "Low priority score",
}
